# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

import sys
import subprocess  # Import the subprocess module for running shell scripts
from PyQt5 import QtCore, QtGui, QtWidgets
import pyrebase

# Firebase Configuration
# GUI Firebase Node Project
config = {
    "apiKey": ""
    "authDomain": "",
    "databaseURL": "",
    "projectId": ""
    "storageBucket": ""
    "messagingSenderId": "",
    "appId": "",
    "measurementId": ""
}

class Ui_MainWindow(object):
    def __init__(self):
        self.db = None
        self.load_detection_process = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 280)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: solid 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(34,36,44);\n"
"}\n"
"\n"
"QLineEdit: hover{\n"
"    border: 2px solid rgb(48,50,62);\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85,170,255);\n"
"    background-color: rgb(43,45,56);\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 140, 240, 40))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.initialize_firebase()
        self.db.child("status").set(1)
        self.db.child("load_detection").set(0)
        self.db.child("terminate").set(0)
        self.pushButton.clicked.connect(self.load_detection)
        self.load_detection_timer = QtCore.QTimer()
        self.load_detection_timer.timeout.connect(self.check_and_run_load_detection)
        self.load_detection_timer.start(1000)

        # Set gui_status to 1 on startup and ensure it stays at 1
        self.db.child("gui_status").set(1)
        self.gui_status_timer = QtCore.QTimer()
        self.gui_status_timer.timeout.connect(lambda: self.db.child("gui_status").set(1))
        self.gui_status_timer.start(5000)  # Update every 5 seconds

    def initialize_firebase(self):
        firebase = pyrebase.initialize_app(config)
        self.db = firebase.database()

        # Timer setup for updating the 'timer' node in Firebase
        self.timer_value = 0
        self.timer = QtCore.QTimer(MainWindow)
        self.timer.timeout.connect(self.update_timer)
        self.timer.start(1000)

        # Listen for changes in the 'status' node and update UI
        self.db.child("status").stream(self.update_status)
        
        # Initialize 'terminate' node for shutdown control
        self.db.child("terminate").set(0)
        self.db.child("terminate").stream(self.check_termination)

        # Path to shutdown script (update if needed)
        self.shutdown_script_path = "/home/grapeleaf/Downloads/GUI/Shutdown.sh"

    def check_termination(self, message):
        terminate_value = message["data"]
        if terminate_value == 1:
            self.db.child("gui_status").set(0)
            self.db.child("load_detection").set(0)
            self.db.child("status").set(0)
            
            MainWindow.close()  # Close the GUI window
            try:
                self.db.child("terminate").set(0)
                subprocess.run(self.shutdown_script_path, shell=True, check=True)  # Run shutdown script
            except subprocess.CalledProcessError as e:
                print(f"Error executing shutdown script: {e}")

    def update_timer(self):
        self.timer_value += 1  
        self.db.child("timer").set(self.timer_value)  

    def update_status(self, message): 
        status = self.db.child("status").get().val()
        if status == 1:
            self.lineEdit.setText("Status ON")
        else:
            self.lineEdit.setText("Status OFF")

    def load_detection(self):
        print("Load Detection button clicked!")
        self.db.child("load_detection").set(1)

    def check_and_run_load_detection(self):
        load_detection_value = self.db.child("load_detection").get().val()

        if load_detection_value == 1:
            # Run the LoadDetection.sh script
            try:
                subprocess.run(["/home/grapeleaf/Downloads/GUI/LoadDetection.sh"], shell=True, check=True)
                
                self.db.child("gui_status").set(2)
                
            except subprocess.CalledProcessError as e:
                print(f"Error executing LoadDetection.sh: {e}")

            # Reset load_detection value in Firebase to 0 after running
            self.db.child("load_detection").set(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grape Leaf Disease Detection"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Status OFF"))
        self.pushButton.setText(_translate("MainWindow", "Load Detection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
